### ISSUE TITLE
Amazon S3 CORS

### ISSUE THREAD

**Issue by thierryskoda** [CrackerakiUA/ngImgCropFullExtended#162] opened 2016-09-05 19:57 UTC
Hi! 

I'm having an error using this library with Amazon S3. If I want to use the directive with an url from Amazon S3 it gives me this error : 

`Image from origin 'https://MY_S3_BUCKET.s3.amazonaws.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.`

In this bucket, I've allowed CORS for everything and it still doesn't work.

Anyone ever had this problem ? Thank you!

**Comment by rickerd** [comment] 2016-09-05 20:24
Amazon is the origin, so the request header should be allowed there not on your localhost

**Comment by thierryskoda** [comment] 2016-09-05 20:32
@rickerd Do you have any example? Does the CORS need to be enable server side? Or I need to do some setup in my Angularjs app? 

Thank you again!

**Comment by thierryskoda** [comment] 2016-09-05 21:11
Is this because the library is using Canvas and this is the problem?

**Comment by CrackerakiUA** [comment] 2016-09-05 21:24
You can access to your image via web browser url? Try also anonymous browser.

**Comment by rickerd** [comment] 2016-09-07 20:14
Closing since the issue is not in the library.
Please see Gitter to get a helping hand.

**Closed as completed by rickerd** 2016-09-07 20:14 UTC

**Comment by adrienbourgeois** [comment] 2016-09-21 06:44
I'm having the same issue with an amazon S3 bucket as well.
When I try to access the image in an incognito chrome window the image is loading properly.
So I assume the error is from the library.

**Comment by rickerd** [comment] 2016-09-21 07:03
Are you sure that the headers are correct?
Loading An image trough a browser or in the cropper is different.

**Comment by adrienbourgeois** [comment] 2016-09-21 07:07
Hi @rickerd , which headers are you talking about?

Here is a sample of my code:

``` html
<img-crop image="fileInfo.url" result-image="myCroppedImage"></img-crop>
```

fileInfo.url is a amazon s3 url that looks something like this: 
https://s3-ap-southeast-2.amazonaws.com/myhost.com/foo/bar/58131/1474440992/original/my_pic.jpg?1474440992

This is loading fine in a browser window.

**Comment by adrienbourgeois** [comment] 2016-09-23 01:00
This plugin is performing a "getImageData" javascript call. I did my homework and from what I understand, by default, that call doesn't allow CORS because it could potentially be used to show images from the hard-drive of the users. That is why if the resource headers don't explicitly allow CORS that error will be thrown. In my scenario, the resource is loaded from our amazon S3 server, so I've reconfigured the header of amazon S3 to explicitly allow CORS and now it is working like a charm.

Here is the most relevant stackoverflow I could find: http://stackoverflow.com/questions/4672643/html5-canvas-getimagedata-and-same-origin-policy

Here is the config I've pushed to my amazon S3 server:

```
<CORSConfiguration>
<CORSRule>
<AllowedOrigin>*</AllowedOrigin>
<AllowedMethod>GET</AllowedMethod>
</CORSRule>
</CORSConfiguration>
```

see: http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html#how-do-i-enable-cors
