### ISSUE TITLE
Lag on the screen when Mouse Down

### ISSUE THREAD

**Issue by vinimendes3** [CrackerakiUA/ngImgCropFullExtended#44] opened 2015-12-30 14:16 UTC
When I'm moving the selected area over the screen, it runs smoothly, but only when I release the cursor it takes a little time to re-rerun.

Can I do something to remove this lag?

![lag_ng_img_crop](https://cloud.githubusercontent.com/assets/3437722/12051772/21896682-aeef-11e5-8167-1ada0d8ec527.gif)

**Comment by CrackerakiUA** [comment] 2016-01-22 22:42
this is an issue we have seen before. I can't reproduce it my self. i Would love to help just need a way to test it.

**Comment by CrackerakiUA** [comment] 2016-02-29 03:27
this is fixed with block rendering, try this out http://codepen.io/Crackeraki/pen/XmEdPx

**Closed as completed by CrackerakiUA** 2016-02-29 03:27 UTC
