### ISSUE TITLE
Crop Error If Width and Height Unspecified

### ISSUE THREAD

**Issue by biblicalph** [CrackerakiUA/ngImgCropFullExtended#95] opened 2016-03-31 14:28 UTC
Hi, 

I have implemented this plugin with ng-file-upload (https://github.com/danialfarid/ng-file-upload) and after much difficulty have been able to get it working. I set my crop area to a width of 100% and min-height for my crop area as well. With these 2 in place, I kept getting an error: 

> cannot get property 0 of null at t.getColor

Is it possible to set width in dimensions such as percentage? Same goes for height. 

Regards

**Comment by karensg** [comment] 2016-04-20 13:29
I just got the same error with IE11 on Windows 10. I think this error also happens in other cases.

```
<img-crop change-on-fly="false" chargement="'Afbeelding laden'" image="picFile" result-image-format="picFile.type" result-image-size="140" result-image="croppedDataUrl"></img-crop>
```

**Comment by CrackerakiUA** [comment] 2016-04-20 13:42
an codepen would be good to track the issue.

**Comment by karensg** [comment] 2016-04-21 08:37
I can not really reproduce it myself. I have an error logging tool installed and I see that this happened.
When I try, it myself, it works for me. Probably there is some special user behavior.

**Comment by CrackerakiUA** [comment] 2016-04-21 11:18
Then i can't see how can i help you. If you find where is the problem and fix it, you can make pr, i will accept it.

**Comment by karensg** [comment] 2016-04-21 11:43
Sure, I will definitely let you know if I can find it. 
The issue created is not mine, I just responded to give more information about it.

**Comment by rickerd** [comment] 2016-09-01 07:52
Closing since starter does not respond and other people cannot re-produce the bug

**Closed as completed by rickerd** 2016-09-01 07:52 UTC
Labels: bug
