### ISSUE TITLE
Cropping is not working with column-count css property

### ISSUE THREAD

**Issue by wickY26** [CrackerakiUA/ngImgCropFullExtended#84] opened 2016-03-10 09:48 UTC
In my case I am using multiple `img-crop` directive in one page. This page has 3 columns and directive is only working at the first column and not for the rest. I created a [codepen](http://codepen.io/anon/pen/MyegEG) for this issue.

in this codepen example you could see it but cannot edit it in my application you cannot even see it. 

any help would be great?

NOTE: I tested it with ie it is working but it is not working with chrome... Interesting ie is working but chrome not :)

**Comment by CrackerakiUA** [comment] 2016-03-10 17:55
Have you tried to use different variables for input?

**Comment by wickY26** [comment] 2016-03-11 07:52
@CrackerakiUA Yes I did it here are some testing case...

Here is my application where I encounter with issue.
If I have img-crop on column 2 or 3 it doesn't show up at all.

![2 columns](https://cloud.githubusercontent.com/assets/5011438/13696309/3d5532d0-e76e-11e5-9745-7c00a82c6785.png)

but if I make screen smaller and move that components into column 1 it is shown

![1column](https://cloud.githubusercontent.com/assets/5011438/13696324/53218b68-e76e-11e5-8f43-10cda7abbc97.png)

only thing I did in this example is pick image then make screen smaller from developer console...

I actually update my [codepen](http://codepen.io/anon/pen/MyegEG) with media query so if you pick an image you will see it will not work for column 2 and 3 but then make screen smaller you will see it will work...

**Comment by CrackerakiUA** [comment] 2016-03-13 00:34
in your example pen i see only one input for adding images, is this how it suppose to be?

**Comment by wickY26** [comment] 2016-03-13 11:16
@CrackerakiUA yes I am using one filepicker if you want you can use one for each it does not related with ui issue.

**Comment by CrackerakiUA** [comment] 2016-03-13 12:10
Trying to understand the issue. When you add an image, you can only move crop area only on first?

**Comment by CrackerakiUA** [comment] 2016-03-13 12:32
The task is to create many different result of an image, correct?

**Comment by wickY26** [comment] 2016-03-13 14:11
@CrackerakiUA no no. Think all columns are independent. Each of them reflect an item and they have no relation at all. Problem is if item is positioned at first column then img-crop is working but if item positioned on other columns different than first column then it is not working...

You can remove first img-crop at the example on codepen if you want so you can see still will not work...

**Comment by CrackerakiUA** [comment] 2016-03-13 14:30
The css you are using braking it. Look here http://codepen.io/anon/pen/XdjRvx?editors=1100
everything looks smooth. I don't have much experience in css, so i can't help you.

**Comment by rickerd** [comment] 2016-07-17 23:28
The issue is not related to the cropper but rather to your css / html.
I will close this issue for now.

If you have a link where we can test and see the results i can try and help you.
Maybe send a message on our chat to get quicker help.
https://gitter.im/CrackerakiUA/ngImgCropFullExtended

**Closed as completed** 2016-07-17 23:28 UTC
Labels: help wanted

**Comment by CrackerakiUA** [comment] 2016-07-18 01:31
@wickY26 check our latest PR, maybe it will help you out. It automatically add size to cropper.
